# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "nvme" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" = {
    device = "/dev/disk/by-uuid/72429584-dda2-4cf1-90d1-4fbf0e27f540";
    fsType = "btrfs";
    options = [ "subvol=root" "compress-force=zstd"];
  };

  fileSystems."/nix" = {
    device = "/dev/disk/by-uuid/72429584-dda2-4cf1-90d1-4fbf0e27f540";
    fsType = "btrfs";
    options = [ "subvol=nix" "compress-force=zstd"];
  };

  fileSystems."/home" = {
    device = "/dev/disk/by-uuid/72429584-dda2-4cf1-90d1-4fbf0e27f540";
    fsType = "btrfs";
    options = [ "subvol=home" "compress-force=zstd"];
  };

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/1D01-BEC5";
    fsType = "vfat";
    options = [ "fmask=0077" "dmask=0077" ];
  };

  swapDevices = [ ];

  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp0s31f6.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlp3s0.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}


